### ISSUE TITLE
Make all in-text references/citations consistent.

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/LakeBonnevilleSM#1]
In-text citations weren't always consistent in formatting. To be consistent, they should be hyperlinked when available and un-bolded. They also need to be checked that they open to a new window and go to the correct place.

**Comment by Mackenzie-Cope** [comment]
- [ ] Hyperlink all publications in citations (that are available)
- [ ] Un-bold bolded citations (Great Salt Lake Levels slide, specifically)
- [ ] Check all hyperlinked citations that they go to the correct publication (I found a few that didn't go to the right place)

**Comment by inkenbrandt** [comment]
Ok, this is done.

**Comment by Mackenzie-Cope** [comment]
Sweet! Thanks for doing that. A couple quick fixes I caught checking through them again:

- [ ] Bonneville Shoreline section, Oviatt, 2020 goes to the Oviat 2015 pub.

- [ ] Bonneville Flood section, Oviatt, 2015 use the direct link instead of the DOI link

- [ ] Drying Up section, Currey and others, 1988 links to 1984 map

- [ ] References, Bills, B.G. link goes to an xml error page

- [ ] References, Pederson, J.L. 2016 can you link straight to the chapter page: https://www.sciencedirect.com/science/article/pii/B9780444635907000020

**Comment by inkenbrandt** [comment]
Ok, this is done

**Comment by Mackenzie-Cope** [comment]
Looks great!
