### ISSUE TITLE
Bonneville Flood section - map clarification/addition

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/LakeBonnevilleSM#10]
On the Bonneville Flood section, is the map showing the extent of the lake after the flood or where the natural dam is? Can we add a point or line where the natural dam is/was on this map?

**Comment by inkenbrandt** [comment]
Its actually a controversial topic. The flood washed away a lot of the evidence needed to accurately delineate the natural dam.  I will add a dotted line showing the approximate place.

**Comment by inkenbrandt** [comment]
Ok, please see my changes.  I have added the flood extent polygon from O'Connor and a dashed red line for the approximate location of the dam.  I have sent O'Connor an email requesting photos of evidence from the Bonneville Flood.

**Comment by Mackenzie-Cope** [comment]
Looks good. If you get photos, that would be good to add too.
