### ISSUE TITLE
Drying Up section - map clarification/addition

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/LakeBonnevilleSM#11]
In the Drying Up section, Do we need the streams to be more prominent in the map because they are referenced in the paragraphs?

**Comment by inkenbrandt** [comment]
I didn't have a good map for that one.  I added a gif I made using a simplified polygon of the lake varying in elevation over time.  I had to cut off the edges because ArcGIS couldn't handle rendering the entire polygon in animation.

**Comment by Mackenzie-Cope** [comment]
I like the gif! I don't love the white spaces on the sides though. Can we try going back to using the modern GSL extent map in the window and then add the gif in the pane and see how that looks?

**Comment by inkenbrandt** [comment]
Done

**Comment by Mackenzie-Cope** [comment]
Looks good! Can you add some additional description for this section about the GSL Desert and the other bodies of water that are highlighted?

Also, do you want that to be the final look for the popups or would something simpler look better? You could maybe add a description in the GSL desert as remnants of Lake Bonneville.

**Comment by inkenbrandt** [comment]
I'll see if I can modify the popup style of that layer.  If not, I will import a custom polygon of the GSL with the proper symbology and popup style.

**Comment by inkenbrandt** [comment]
Done

**Comment by Mackenzie-Cope** [comment]
Looks good
