### ISSUE TITLE
Shoreline shapes' symbology is inconsistent among the slides.

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/LakeBonnevilleSM#12]
The shoreline shapes in the different slides have different symbology to them. They are different blues or have darker/lighter outlines. Can we make them consistent in these slides:

- Introduction (?) - Maybe we want this one different?
- Stansbury Shoreline
- Bonneville Shoreline
- Provo Shoreline
- Rebound
- Drying up (possibly add the shape on top of the basemap with a popup just to match the others? I'll leave it up to you, @inkenbrandt to see how it looks and if it makes sense to add it.)

**Comment by inkenbrandt** [comment]
Each fill was given a color of #43ABEB and transparency of 46%
Each stroke was given a color of #4C64C9, stroke width of 1 and transparency of 0%
I added an esri lakes layer to emphasize the current state of lakes in the West for the Drying up page

**Comment by inkenbrandt** [comment]
Done

**Comment by Mackenzie-Cope** [comment]
Looks good
