### ISSUE TITLE
Filling the Lake

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/LakeBonnevilleSM#13]
> But the change in the land surface by the volcanoes caused it go south, at first pooling by Grace, Idaho, then later eroding out the Oneida Narrows, and flowing south through Cache Valley into to the young Lake Bonneville. 

**Suggested change to remove "but" from the beginning of the sentence:**
Volcanic events changed the land surface which redirected the river southward, at first pooling by Grace, Idaho, then later eroding out the Oneida Narrows, and flowing south through Cache Valley into to the young Lake Bonneville.

**Comment by inkenbrandt** [comment]
Done
