### ISSUE TITLE
Bonneville Flood

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/LakeBonnevilleSM#14]
> At about 18,000 years ago (Oviatt 2015), a natural dam at the northernmost part of Lake Bonneville failed, causing a massive flood to rush into Idaho, along the Snake River and into the Colombia River.

**Suggested change (remove "At" and fix "Colombia" spelling):**
About 18,000 years ago (Oviatt 2015), a natural dam at the northernmost part of Lake Bonneville failed, causing a massive flood to rush into Idaho, along the Snake River and into the Columbia River.

> The flood drained 380 cubic miles of water in about six weeks, with an average and maxium flows of 15 and 30 million cubic feet per second, respectively (Malde, 1968, O'Connor, 2016).

**Suggested change (I think "flows" is "flow" in this case, or remove "an" to keep it as "flows". Fixed "maxium" spelling):**
The flood drained 380 cubic miles of water in about six weeks, with an average and maximum flow of 15 and 30 million cubic feet per second, respectively (Malde, 1968, O'Connor, 2016).

**Comment by inkenbrandt** [comment]
Great! Fixed.
