### ISSUE TITLE
M. Hylland Review

### ISSUE THREAD

**Issue by marshallrobinson** [UGS-GIO/LakeBonnevilleSM#16]
Hey @mikehylland,

Paul I. has completed this Lake Bonneville story-map, and put it through the appropriate review, so it is now ready for your review comments when you have time. Thanks

https://arcg.is/1yaCLy0

**Comment by Mackenzie-Cope** [comment]
@mikehylland 

Stephanie has done a technical review of Paul's storymap now. He took care of all her comments and suggestions so you can take a look now. Thanks!

https://arcg.is/1yaCLy0

**Comment by Mackenzie-Cope** [comment]
Comments have been addressed!
