### ISSUE TITLE
Stephanie Carney Review

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/LakeBonnevilleSM#17]
Hey @geowomansteph,

Paul Inkenbrandt has completed this Lake Bonneville storymap. Will you add this to your list for technical review? Thank you!

https://arcg.is/1yaCLy0

**Comment by Mackenzie-Cope** [comment]
@inkenbrandt 

Attached are Stephanie's comments. Please go through and address them when you have time. Thanks!

[Lake Bonneville story map edits.docx](https://github.com/UGS-GIO/LakeBonnevilleSM/files/6006405/Lake.Bonneville.story.map.edits.docx)

**Comment by inkenbrandt** [comment]
I have addressed the comments.  I take issue with the comma in the thousands place, as it does not follow the UGS style guide, but I added those commas.

**Comment by Mackenzie-Cope** [comment]
Thanks for taking care of those comments, @inkenbrandt. Closing this issue.
