### ISSUE TITLE
Add map description to each slide.

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/LakeBonnevilleSM#2]
I think a statement or map description at the bottom of **each slide** is necessary to make it obvious what the user is looking at. This could also be a description of what each layer is and why we're showing it. 

Try it bolded and small-ish at the bottom of the slide. I think that would make it obvious it is a caption to the large map (or photo).

For example, in the "Filling the Lake" section, I was confused about the purple streams layer and how it was applicable to what the paragraphs were explaining. A short and concise description would be helpful. 
Something like, "The map is showing the new flow direction of the Bear River. The purple lines indicate the major streams that were also affected by the change in flow." (or whatever their purpose is.... sorry.)

**Comment by inkenbrandt** [comment]
Do you know how to add that? I am unsure how to add floating text on a map at the bottom of a storymap slide. Maybe an annotation in the map?

**Comment by Mackenzie-Cope** [comment]
I am not familiar with this storymap template so I'm not sure how you would do that. I was thinking you could add it as a last paragraph or sentence in your description text.

**Comment by inkenbrandt** [comment]
Done

**Comment by Mackenzie-Cope** [comment]
Looks good to me! Thanks!
