### ISSUE TITLE
If clicking or interaction is enabled, popups need to be cleaned up or removed.

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/LakeBonnevilleSM#3]
Popups I noticed that weren't as clean:

- FILLING THE LAKE - UtahMajor_Streams layer
- STANSBURY SHORELINE - lake bonneville shape
- REBOUND - contour lines
- GREAT SALT LAKE DRAINAGE - watershed layer (this one may be fine, is the hydrologic unit code useful in the popup?)

**Comment by inkenbrandt** [comment]
Done.  I would like to retain the hydrologic unit code (note that this popup has been cleaned up).

**Comment by Mackenzie-Cope** [comment]
Looks great!
