### ISSUE TITLE
Lake Bonneville shape popup is inconsistent across slides

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/LakeBonnevilleSM#4]
Some slides allowed the click on Lake Bonneville with a popup. Is there a reason some slides allow that popup and others don't? Or do they just need to be made consistent across slides, either allow or don't?

**Comment by Mackenzie-Cope** [comment]
@inkenbrandt The Provo Shoreline section is the only one where Lake Bonneville does not have a popup and is not clickable. Can we add a popup just for consistency's sake?

**Comment by inkenbrandt** [comment]
This is now done.

**Comment by Mackenzie-Cope** [comment]
Looks good!
