### ISSUE TITLE
Quick Fixes by section

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/LakeBonnevilleSM#5]
Title Slide
- [x] Remove the date?

Filling the Lake
- [x] Fix Oneida Narrows link
- [x] Figure "changing the course of the bear river" is tiny when you click to expand

Stansbury Shoreline
- [x] Figure "approximate lake elevations and phases" is tiny when you click to expand

Bonneville Shoreline
- [x] Figure is tiny when you click to expand

Bonneville Flood
- [x] Change hyperlink text to "Read more about radiocarbon calibration."

Provo Shoreline
- [x] Figure of graph is tiny when you click to expand
- [x] The caption on the Gilbert figure is a little vague. Can you add that it's the Logan River Delta or Provo Delta? Are all these figures of the same area? The captions could be a little clearer.

Rebound
- [x] Delete extra space before 3rd paragraph first sentence

Great Salt Lake Levels
- [x] Delete first citation. I think we can just use the second one and reference all of it to the pub once.
- [x] Bold the instructions to the interactive timeline (this could be the map description for this section. See Issue #2)

Bear River
- [x] Delete extra space before paragraph 2 first sentence.

References
- [x] Make the text smaller on this slide.
- [x] Should we link to the pubs here? I'm torn.

**Comment by inkenbrandt** [comment]
I couldn't figure out how to get rid of the date.  I think it is autogenerated by Storymaps.  It updates when I edit.

**Comment by inkenbrandt** [comment]
It is actually really hard to change font size on these slides!  I tried to shrink the references, but could not.

**Comment by inkenbrandt** [comment]
Ok, I think this is done.

**Comment by Mackenzie-Cope** [comment]
Sweet! Thanks!
