### ISSUE TITLE
Bear River Layer Arrows

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/LakeBonnevilleSM#6]
The Bear River layer was a little confusing in a couple places in the storymap. I'm not sure what to do about them.

In the "Filling the Lake" and "Bear River" sections, there are arrows on the Bear River lines. They are a little scrambled and close together in places, making it hard to see what direction they are pointing. I think the arrows need to be simplified or the direction of flow needs to be shown a different way. Any ideas?

**Comment by inkenbrandt** [comment]
I removed the layer and changed the base map.  I wasn't able to clean up the arrow placement.  Hopefully the depiction of the base map is clear enough.

**Comment by Mackenzie-Cope** [comment]
I think the new dotted line and basemap do the job just fine. 

The volcano icon is pretty blurry though. Can we use an icon that's more clear or a shape where the extent of the volcanics occurred? Was it just one volcano or an area of activity?

**Comment by Mackenzie-Cope** [comment]
Also, this slide is the only one with the side pane in this format. Can we go back to the other pane format for consistency?

**Comment by inkenbrandt** [comment]
Ok, I found a thesis with a good delineation of the basalt flows that contributed to the diversion of the Bear River:
https://digitalcommons.usu.edu/cgi/viewcontent.cgi?article=2075&context=gradreports

It will take me a couple of days to digitize their GIS, but I think it will make for a clearer picture.

**Comment by inkenbrandt** [comment]
In the mean time, I have replaced the fuzzy volcano with a triangle.

**Comment by inkenbrandt** [comment]
Done

**Comment by Mackenzie-Cope** [comment]
Looks good!
