### ISSUE TITLE
Last section, "Bear River" relevancy unclear

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/LakeBonnevilleSM#7]
The last slide/section, "Bear River"

The purpose or relevancy of this slide is not immediately apparent. Is it the only river that makes it to GSL? Or the biggest contributor to GSL? I think it needs to be obviously stated why this is the last slide and why it's important to the Lake Bonneville story as a whole?

A final statement for closure would be good here too. Maybe about how the Bear River is important as the last chapter in this story?

**Comment by inkenbrandt** [comment]
I deleted this slide and all of its content.

**Comment by Mackenzie-Cope** [comment]
Sounds good.
