### ISSUE TITLE
Rebound section - confusing map

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/LakeBonnevilleSM#9]
In the Rebound section, the current-day lake expanse is on the map, but it's kind of confusing on how it got from the Provo shoreline to this one. Should the Provo Shoreline still be here? Maybe the map description (see issue #2) can address this confusion.

**Comment by inkenbrandt** [comment]
I changed it to the Provo Shoreline.  I also added a description and contour labels.

**Comment by Mackenzie-Cope** [comment]
Looks good.
